### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by ricefiel** [tkleijkers/homebridge-visonic-powerlink3#1]
When I try to install it gives the following error:

npm install -g homebridge-visonic-powerlink3
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/homebridge-visonic-powerlink3 - Not found
npm ERR! 404 
npm ERR! 404  'homebridge-visonic-powerlink3@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

Has the project been deleted?

**Comment by tkleijkers** [comment]
You have to clone the repository to use this code. It is not (yet) added to the NPM package system.
