### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by dtripp94** [tkleijkers/homebridge-visonic-powerlink3#2]
hello. I cannot get this package to install. is there an updated version? Many thanks

**Comment by tkleijkers** [comment]
Please describe your error so that we can help you.

**Comment by dtripp94** [comment]
Thanks for your reply. I am very new to this. Added the package to NPM

pi@raspberrypi:~ $ npm install -g homebridge-visonic-powerlink3
npm ERR! code E404
npm ERR! 404 Not Found: visonic-powerlink3@^1.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-10-23T16_41_27_600Z-debug.log

**Comment by tkleijkers** [comment]
You have to install the package visonic-powermail3 from https://github.com/tkleijkers/visonic-powerlink3. It is not available via NPM.
