### ISSUE TITLE
API Version Parameter

### ISSUE THREAD

**Issue by JSVarga** [tkleijkers/homebridge-visonic-powerlink3#20]
I have seen issues on other threads of problems because their provider updated to API to 10.0, however my issue is my new provider is still on API version 8.0 so the call to version 9.0 fails. Would it be possible to make the API version number a parameter we could configure according to the version our providers have installed?

**Comment by damianfm** [comment]
Just change "self.restVersion" from 9.0 to 8.0 in /usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js and it will run with your provider

**Comment by JSVarga** [comment]
Thank you! Works, just works.

**Comment by tkleijkers** [comment]
Version is now configurable in the settings
