### ISSUE TITLE
rest_api tycomonitor changed “again”

### ISSUE THREAD

**Issue by damianfm** [tkleijkers/homebridge-visonic-powerlink3#21]
Hi!
New tycomonitor rest_api update again… (from 9.0 to 10.0)

Workaround:

Just change "self.restVersion" from 9.0 to 10.0 in /usr/lib/node_modules/homebridge-visonic-powerlink3/node_modules/visonic-powerlink3/index.js

**Comment by Raptor0014** [comment]
How do I actually get into that directory to change it?

**Comment by tkleijkers** [comment]
Latest version updates the version and adds config setting for this version
