### ISSUE TITLE
Zone Control

### ISSUE THREAD

**Issue by StuFull** [tkleijkers/homebridge-visonic-powerlink3#4]
Hi,

Thanks for the great add on, it's really useful.

Do you think it would be possible to have support for multiple zones?  For example I have 2 zones, one for the house and one for the garage, which can be armed or disarmed independently.

**Comment by tkleijkers** [comment]
If the API of Visonic supports multiple zones, it should be able to work. However there is no good documentation of this API. I found this library (https://github.com/barcar/visonic_control) which has scripts to arm/disarm but also does not implement multiple zones.
