### ISSUE TITLE
Plugin Improvements

### ISSUE THREAD

**Issue by nitaybz** [tkleijkers/homebridge-visonic-powerlink3#8]
Hey...

Following our recent improvements to the plugin I thought maybe we can add some more...
I'm just not sure how to get more data out of the device... I would want to add more modes like "triggered" and maybe "status tempered" when one of the sensors were tempered... can you help me investigate?
how did you get to those API endpoints? are there any documentations?

Thanks

**Comment by tkleijkers** [comment]
There isn't any official doc, but the API now is based on https://github.com/And3rsL/VisonicAlarm2

**Comment by davidt94** [comment]
Also spotted this. Not sure if this is more up to date. https://github.com/chrisns/visonic_v8

**Comment by nitaybz** [comment]
the latest is very interesting and up to date... I contacted the creator to see if we can overcome an issue I spotted...
If it will be fixed I think we should consider using that library as it contains much more endpoints and options....
I'm trying to investigate now wether it is possible to extract sensor events and possibly add them to homekit.
or at least find a way to integrate alarm trigger or tempered events.

**Comment by davidt94** [comment]
@nitaybz sounds promising.

I think you would be able to get devices plulled though and get reliable sensors for open and close devices (door and window contacts). As these status are reported back to the Visonic-Go app.

I dont think motion detectors are going to work. The data for motion alerts is not reported back to the server unfortunately.
