### ISSUE TITLE
hoobs v 4

### ISSUE THREAD

**Issue by rytisrytis** [tkleijkers/homebridge-visonic-powerlink3#9]
can't get plugin  up and running on hoobs V4 :(

**Comment by tkleijkers** [comment]
This plugin is developed for homebridge and is not tested for hoobs.

**Comment by rytisrytis** [comment]
Good morning, 
Thank you for your message. 
it was working on hoobs V3 without any problems. By some reason after upgrading to v4 it stopped 
Any advise please? 
Thank you

**Comment by tkleijkers** [comment]
I have no idea as I'm not familiar with Hoobs.
